# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rssfly/extractor/mangaplus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n rssfly/extractor/mangaplus.proto\x12\x1arssfly.extractor.mangaplus"D\n\x0eSeriesResponse\x12\x32\n\x06series\x18\x01 \x01(\x0b\x32".rssfly.extractor.mangaplus.Series"A\n\x06Series\x12\x37\n\x06series\x18\x08 \x01(\x0b\x32\'.rssfly.extractor.mangaplus.SeriesInner"\xa2\x02\n\x0bSeriesInner\x12\x42\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32-.rssfly.extractor.mangaplus.SeriesDescription\x12\r\n\x05thumb\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x12\n\nbackground\x18\x04 \x01(\t\x12\x10\n\x08unknown1\x18\x05 \x01(\t\x12\x14\n\x0cuser_message\x18\x07 \x01(\t\x12\x35\n\x08\x63hapters\x18\t \x03(\x0b\x32#.rssfly.extractor.mangaplus.Chapter\x12<\n\x0flatest_chapters\x18\n \x03(\x0b\x32#.rssfly.extractor.mangaplus.Chapter"\x80\x01\n\x11SeriesDescription\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x16\n\x0ethumb_portrait\x18\x04 \x01(\t\x12\x17\n\x0fthumb_landscape\x18\x05 \x01(\t\x12\x0f\n\x07unknown\x18\x06 \x01(\x03"\x86\x01\n\x07\x43hapter\x12\x11\n\tseries_id\x18\x01 \x01(\x03\x12\x12\n\nchapter_id\x18\x02 \x01(\x03\x12\x0e\n\x06number\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x11\n\tthumbnail\x18\x05 \x01(\t\x12\x10\n\x08unknown1\x18\x06 \x01(\x03\x12\x10\n\x08unknown2\x18\x07 \x01(\x03\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "rssfly.extractor.mangaplus_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SERIESRESPONSE._serialized_start = 64
    _SERIESRESPONSE._serialized_end = 132
    _SERIES._serialized_start = 134
    _SERIES._serialized_end = 199
    _SERIESINNER._serialized_start = 202
    _SERIESINNER._serialized_end = 492
    _SERIESDESCRIPTION._serialized_start = 495
    _SERIESDESCRIPTION._serialized_end = 623
    _CHAPTER._serialized_start = 626
    _CHAPTER._serialized_end = 760
# @@protoc_insertion_point(module_scope)
